// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFZjNoU02-OiMnc250nhDIs6PuMkP17M',
    appId: '1:939590957303:web:637c7736013d0cfdaa7bf2',
    messagingSenderId: '939590957303',
    projectId: 'weather-app-907ed',
    authDomain: 'weather-app-907ed.firebaseapp.com',
    storageBucket: 'weather-app-907ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9QK3LRYuXrmKuTqZUjgewD_S8xu80cGk',
    appId: '1:939590957303:android:536a7362a5470866aa7bf2',
    messagingSenderId: '939590957303',
    projectId: 'weather-app-907ed',
    storageBucket: 'weather-app-907ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhhpWDIKgO5UcmtgRnaOuoA1PKQ10UE1A',
    appId: '1:939590957303:ios:5da543ef1c26f92caa7bf2',
    messagingSenderId: '939590957303',
    projectId: 'weather-app-907ed',
    storageBucket: 'weather-app-907ed.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhhpWDIKgO5UcmtgRnaOuoA1PKQ10UE1A',
    appId: '1:939590957303:ios:5da543ef1c26f92caa7bf2',
    messagingSenderId: '939590957303',
    projectId: 'weather-app-907ed',
    storageBucket: 'weather-app-907ed.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgFZjNoU02-OiMnc250nhDIs6PuMkP17M',
    appId: '1:939590957303:web:1acb99e72fa4a012aa7bf2',
    messagingSenderId: '939590957303',
    projectId: 'weather-app-907ed',
    authDomain: 'weather-app-907ed.firebaseapp.com',
    storageBucket: 'weather-app-907ed.firebasestorage.app',
  );
}
